### ISSUE TITLE
Update set date for use GMT date with timezone

### ISSUE THREAD

**Issue by dave-code-ruiz** [ralphm2004/broadlink-thermostat#4]
Hi ralphm2004, 

Sorry for my english, great repo, i use it with great results, thanks a lot.

I create a "Fork" in my account with a little change "Update set date for use GMT date with timezone"

It is my first contribution, sorry if it is bad.

I try to create a "pull request" to propose you this change but i don´t know how to do it.

I use a hassbian in raspberrypi and my change work fine!

Thnks

**Comment by ralphm2004** [comment]
thanks @fcastroruiz
